name: nem-data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - cufflinks-py=0.17.3
  - flake8=3.7.9
  - ipykernel=5.1.4
  - ipympl=0.5.6
  - ipywidgets=7.5.1
  - jupyter_client=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.7
  - jupyterthemes=0.20.0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - nodejs=13.10.1
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.2
  - pip=20.0.2
  - plotly=4.5.2
  - python=3.6.10
  - scipy=1.4.1
  - pip:
    - "--editable=git+https://github.com/prakaa/NEMOSIS.git@pocket-rocket-nemosis"
    - feather-format==0.4.0
    - joblib==0.14.1
    - pyarrow==0.16.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - urllib3==1.25.8
    - xlrd==1.2.0

