name: nem-data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - cufflinks-py=0.17.3
  - fastparquet
  - flake8=3.7.9
  - ipympl=0.5.6
  - ipywidgets=7.5.1
  - jupyterlab=1.2.7
  - jupyterthemes=0.20.0
  - matplotlib=3.2.1=0
  - nodejs=13.10.1
  - numpy=1.18.1
  - pandas=1.0.2
  - pip=20.0.2
  - plotly=4.5.2
  - python=3.6.10
  - pip:
    - feather-format==0.4.0
    - joblib==0.14.1
    - pyarrow==0.16.0
    - pyqt5-sip==4.19.18
    - xlrd==1.2.0

